version: "2"
services:
  rancher:
    image: rancher/server:stable
    expose:
      - 8080
    networks:
      - default
      - reverse-proxy
    volumes:
      - ./rancher:/var/lib/mysql
    env_file:
      - .env
    restart: unless-stopped
networks:
  reverse-proxy:
    external:
      name: reverse-proxy

